In [15]:
# Dependências
 
from sklearn import tree
import pandas as pd
import numpy as np
import sklearn.metrics as metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [65]:
# Árvore de Decisão

filePath = 'data/titles.csv'
df = pd.read_csv(filePath)

le = preprocessing.LabelEncoder()
target = le.fit_transform(df['tmdb_popularity'].fillna(0))
data = le.fit_transform(df['genres'].fillna(0))

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.4)

X_trainn = np.array(X_train).reshape(-1,1)
X_testt = np.array(X_test).reshape(-1,1)

clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3) 
clf = clf.fit(X_trainn, y_train) 

predictions = clf.predict(X_testt)

print("\nMatriz de confusão detalhada:\n", pd.crosstab(y_test, predictions, rownames=['Real'], colnames=['Predito'], margins=True, margins_name='Todos'))

print("Relatório sobre a qualidade:\n")
print(metrics.classification_report(y_test, predictions))



Matriz de confusão detalhada:
 Predito     0    2  Todos
Real                     
0          29    1     30
1           1    0      1
2           8    2     10
3           0    1      1
5           1    0      1
...       ...  ...    ...
5194        1    0      1
5196        1    0      1
5197        1    0      1
5199        1    0      1
Todos    2158  297   2455

[2268 rows x 3 columns]
Relatório sobre a qualidade:

              precision    recall  f1-score   support

           0       0.01      0.97      0.03        30
           1       0.00      0.00      0.00         1
           2       0.01      0.20      0.01        10
           3       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          19       0.00      0.00 

c:\Users\au.assis\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\au.assis\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\au.assis\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

In [65]:
# Regressão Linear

filePath = 'data/titles.csv'
df = pd.read_csv(filePath)

df.drop('id',axis=1,inplace=True)
df.drop('title',axis=1,inplace=True)
df.drop('type',axis=1,inplace=True)
df.drop('description',axis=1,inplace=True)
df.drop('release_year',axis=1,inplace=True)
df.drop('age_certification',axis=1,inplace=True)
df.drop('runtime',axis=1,inplace=True)
df.drop('seasons',axis=1,inplace=True)
df.drop('imdb_id',axis=1,inplace=True)
df.drop('imdb_score',axis=1,inplace=True)
df.drop('imdb_votes',axis=1,inplace=True)
df.drop('production_countries',axis=1,inplace=True)
df.drop('genres', axis=1, inplace=True)

print(df.columns)

normalized_df=(df-df.min())/(df.max()-df.min())

votes_transform = le.fit_transform(df['tmdb_score'].fillna(0))
popularity_transform = le.fit_transform(df['tmdb_popularity'])

x = df[['tmdb_score', 'tmdb_popularity']].fillna(0)
y = df['tmdb_popularity'].fillna(0)
print(x.head())
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=50)

# Aqui criamos o modelo preditor 
modelopreditor = LinearRegression() 
#Aqui ocorre o aprendizado 
modelopreditor.fit(X_train,y_train) 
#Imprimindo os coeficientes com os nomes das colunas 
coeff = pd.DataFrame(modelopreditor.coef_,x.columns,columns=['Coeficiente'])
print(coeff)



Index(['tmdb_popularity', 'tmdb_score'], dtype='object')
   tmdb_score  tmdb_popularity
0       0.000            0.601
1       7.782          106.361
2       7.406           33.160
3       8.020           24.616
4       7.246           75.699
0      0.601
1    106.361
2     33.160
3     24.616
4     75.699
Name: tmdb_popularity, dtype: float64
                  Coeficiente
tmdb_score      -1.527378e-15
tmdb_popularity  1.000000e+00


In [ ]:
# KNN
d = pd.read_csv('/content/titles.csv')

#Criando labelEncoder
le = preprocessing.LabelEncoder()
# Criando a variável alvo
alvo = d['tmdb_popularity']
#Convertendo String Labels para números
countries_encoded = le.fit_transform(d['production_countries'])
genres_encoded = le.fit_transform(d['genres']) 
alvo = le.fit_transform(alvo)

carac = list(zip(countries_encoded,genres_encoded))
modelo = KNeighborsClassifier(n_neighbors=3)
# Treinando o modelo usando os ajustes de treinamento.
modelo.fit(carac,alvo)
#Predito
predito = modelo.predict([[100,20],[29,300],[58,74]]) 

predito

In [63]:
# Naive Bayes

import numpy as np

# Criar um dataset

filePath = 'data/titles.csv'
df = pd.read_csv(filePath)

# Primeira Característica 
popularidade = np.array(df['tmdb_popularity'].head())
# Segunda Característica 
generos = np.array(df['tmdb_score'].head().fillna(10))
# Variavel alvo 
recomendar = le.fit_transform(['Não','Sim','Não','Sim','Sim'])

print(popularidade)
print(generos)
print(recomendar)

# convertendo string labels para numeros 
alvo = recomendar

# Combinando clima e temp em um unica lista de tuplas 
carac = list(zip(popularidade,generos))

#Importa a biblioteca do modelo Naive Bayes Gaussiano 
from sklearn.naive_bayes import GaussianNB 
import numpy as np 
# Cria um classificador Gaussiano 
modelo = GaussianNB() 
# Treinando o modelo usando os ajustes de treinamento.
modelo.fit(carac,alvo) 
#Predito 
predito = modelo.predict([[40, 10], [100, 7], [40, 2]]) # 2:Nublado, 2:Suave print(predito)
predito


[  0.601 106.361  33.16   24.616  75.699]
[10.     7.782  7.406  8.02   7.246]
[0 1 0 1 1]


array([0, 1, 0], dtype=int64)